### ISSUE TITLE
bio tab not listed if user does not have dsc.bio account linked - suggestion

### ISSUE THREAD

**Issue by MemLiveOn** [Ser-Ames/discord-bio#6]
I am so sorry if this isn't the proper way to post suggestions. I legit have never used github, and am still learning.

I don't know how easy this would be, if you could just use the api connection to do this, or even simpler,
if content: "looks like this person doesn't have a discord.bio profile", display: none.
I'm sure this could be easily done in a css, but I thought I could mention the suggestion.

**Comment by Ser-Ames** [comment]
Yeah this should be possible to do, @NurMarvin would it be possible for you to implement with maybe a setting that will enable it?

**Comment by NurMarvin** [comment]
Sure thing, I'll add it later since I'm currently have work but I'll get at it right when I have time.
